export const REQUEST_NOTEBOOKS = 'REQUEST_NOTEBOOKS';
export const RECEIVE_NOTEBOOKS = 'RECEIVE_NOTEBOOKS';

export const REQUEST_NOTEBOOK = 'REQUEST_NOTEBOOK';
export const RECEIVE_NOTEBOOK = 'RECEIVE_NOTEBOOK';
