export const REQUEST_FEED = 'REQUEST_FEED';
export const RECEIVE_FEED = 'RECEIVE_FEED';

export const REQUEST_NOTEBOOK = 'REQUEST_NOTEBOOK';
export const RECEIVE_NOTEBOOK = 'RECEIVE_NOTEBOOK';

export const REQUEST_COMMENTS = 'REQUEST_COMMENTS';
export const RECEIVE_COMMENTS = 'RECEIVE_COMMENTS';
export const CREATE_COMMENT = 'CREATE_POST';
export const CREATE_COMMENT_SUCCESS = 'CREATE_POST_SUCCESS';
