export const REQUEST_FEED = 'REQUEST_FEED';
export const RECEIVE_FEED = 'RECEIVE_FEED';

export const REQUEST_NOTEBOOK = 'REQUEST_NOTEBOOK';
export const RECEIVE_NOTEBOOK = 'RECEIVE_NOTEBOOK';

export const REQUEST_COMMENTS = 'REQUEST_COMMENTS';
export const RECEIVE_COMMENTS = 'RECEIVE_COMMENTS';
export const CREATE_COMMENT = 'CREATE_POST';
export const CREATE_COMMENT_SUCCESS = 'CREATE_POST_SUCCESS';
export const REQUEST_SEARCH = 'REQUEST_SEARCH';
export const COMMENT_PANE_UPDATE = 'COMMENT_PANE_UPDATE';
export const SELECT_PAGE_FOR_COMMENTS = 'SELECT_PAGE_FOR_COMMENTS';
